### ISSUE TITLE
Remove `padding-line-between-statements` rule

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/eslint-config#5]
I would prefer not to include stylistic rules.
When having a lot of imports, it seems fine to me to make use of a new line to create some structure if needed.

**Comment by gvdp** [comment]
I'll remove it because it's being deprecated anyway, but I think there is something to say about including this, because it's not something Prettier can do and it does enforce more consistency in the codebase.

These stylistic rules seem to be split off into a new package: https://eslint.style/guide/why

**Comment by bertdeblock** [comment]
Seems like it would be consistency solely for the sake of consistency. Newlines are used throughout every codebase to group related variables, code, ... I don't really understand why it should be disallowed only for imports then.
