### ISSUE TITLE
Why does the `qunit/require-expect` rule config deviate from the recommended config?

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/eslint-config#8]
I would rather keep following the recommended config.

**Comment by gvdp** [comment]
The default for this changed not too long ago:
[docs/rules/require-expect.md
](https://github.com/platinumazure/eslint-plugin-qunit/commit/1c5935b7559212875de7b26b417028bb98f61659)

We have a lot of tests still which use `assert.expect()` because an assertion is done in a callback somewhere. Maybe it would be better to rewrite these but I'm not sure it's possible in every case. In these cases it's still better to use the `except-simple` setting. 

Also not really sure why the default is to never use `assert.expect()` , qunit provides that functionality for a reason.

**Comment by bertdeblock** [comment]
Yup, and I would prefer to follow that (new) default in this shared config, so basically removing our custom configuration. If one of our projects still uses `assert.expect()` heavily, then the custom configuration should go in said project.

> Also not really sure why the default is to never use assert.expect() , qunit provides that functionality for a reason.

Probably that reason doesn't really hold up anymore today according to the community, otherwise there wouldn't be a rule against it.
